const playDL = require('play-dl');
const { getVoiceConnection, createAudioPlayer, createAudioResource, AudioPlayerStatus } = require('@discordjs/voice');
const MusicCommandHandler = require('./MusicClassCommandHandler.js');


class MusicPlayerHandler {

    constructor(guild) {
        this.guild = guild;
        this.player = null;
    }

    async play() {
        const serverInfo = MusicCommandHandler.globalQueue.get(this.guild.id);

        if (typeof serverInfo.songs === 'undefined' || serverInfo.songs.length === 0) {
            serverInfo.connection.destroy();
            MusicCommandHandler.globalQueue.delete(guild.id);
        }

        let resource = await MusicPlayerHandler.serialiseSong(serverInfo.songs[0].url);


        this.player = createAudioPlayer();
        serverInfo.connection.subscribe(this.player);
        
        this.player.play(resource);

        this.player.addListener("stateChange", async (oldOne,newOne) => {
            if (newOne.status=="idle") {
                serverInfo.songs.shift();
                if (serverInfo.songs[0]) {
                    let newResource = await MusicCommandHandler.serialiseSong(serverInfo.songs[0].url);
                    this.player.play(newResource);
                } else {
                    serverInfo.connection.destroy();
                    MusicCommandHandler.globalQueue.delete(this.guild.id);
                    
                }
            }
        });
    }

    /**
     * Creates a resource stream from the given video
     * 
     * @param {*} song The song metadata generated by the playDL API
     * @returns The created audio resource 
     */
     static async serialiseSong(song) {
        let stream = await playDL.stream(song);

        let resource = createAudioResource(stream.stream, {
            inputType: stream.type
        });
        return resource;
    }

}

module.exports = MusicPlayerHandler;